/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SecondService.h"
#include "thrift/async/TAsyncChannel.h"
#include "SecondService.tcc"

namespace thrift { namespace test {

}} // namespace

