/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "StressTest_constants.h"

namespace test { namespace stress {

const StressTestConstants g_StressTest_constants;

StressTestConstants::StressTestConstants() {
}

}} // namespace

