#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'tutorial_types'

INT32CONSTANT = 9853

MAPCONSTANT = {
  %q"hello" => %q"world",
  %q"goodnight" => %q"moon",
}

