/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ChildService.h"
#include "thrift/async/TAsyncChannel.h"
#include "ChildService.tcc"

namespace apache { namespace thrift { namespace test {

}}} // namespace

