/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Inherited_H
#define Inherited_H

#include <thrift/TDispatchProcessor.h>
#include "DebugProtoTest_types.h"
#include "Srv.h"

namespace thrift { namespace test { namespace debug {

class InheritedIf : virtual public SrvIf {
 public:
  virtual ~InheritedIf() {}
  virtual int32_t identity(const int32_t arg) = 0;
};

class InheritedIfFactory : virtual public SrvIfFactory {
 public:
  typedef InheritedIf Handler;

  virtual ~InheritedIfFactory() {}

  virtual InheritedIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SrvIf* /* handler */) = 0;
};

class InheritedIfSingletonFactory : virtual public InheritedIfFactory {
 public:
  InheritedIfSingletonFactory(const boost::shared_ptr<InheritedIf>& iface) : iface_(iface) {}
  virtual ~InheritedIfSingletonFactory() {}

  virtual InheritedIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SrvIf* /* handler */) {}

 protected:
  boost::shared_ptr<InheritedIf> iface_;
};

class InheritedNull : virtual public InheritedIf , virtual public SrvNull {
 public:
  virtual ~InheritedNull() {}
  int32_t identity(const int32_t /* arg */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Inherited_identity_args__isset {
  _Inherited_identity_args__isset() : arg(false) {}
  bool arg;
} _Inherited_identity_args__isset;

class Inherited_identity_args {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

  Inherited_identity_args() : arg(0) {
  }

  virtual ~Inherited_identity_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t arg;

  _Inherited_identity_args__isset __isset;

  void __set_arg(const int32_t val) {
    arg = val;
  }

  bool operator == (const Inherited_identity_args & rhs) const
  {
    if (!(arg == rhs.arg))
      return false;
    return true;
  }
  bool operator != (const Inherited_identity_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Inherited_identity_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Inherited_identity_pargs {
 public:

  static const char* ascii_fingerprint; // = "E86CACEB22240450EDCBEFC3A83970E4";
  static const uint8_t binary_fingerprint[16]; // = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};


  virtual ~Inherited_identity_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int32_t* arg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Inherited_identity_result__isset {
  _Inherited_identity_result__isset() : success(false) {}
  bool success;
} _Inherited_identity_result__isset;

class Inherited_identity_result {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};

  Inherited_identity_result() : success(0) {
  }

  virtual ~Inherited_identity_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t success;

  _Inherited_identity_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Inherited_identity_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Inherited_identity_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Inherited_identity_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Inherited_identity_presult__isset {
  _Inherited_identity_presult__isset() : success(false) {}
  bool success;
} _Inherited_identity_presult__isset;

class Inherited_identity_presult {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};


  virtual ~Inherited_identity_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t* success;

  _Inherited_identity_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class InheritedClient : virtual public InheritedIf, public SrvClient {
 public:
  InheritedClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    SrvClient(prot, prot) {}
  InheritedClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    SrvClient(iprot, oprot) {}
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t identity(const int32_t arg);
  void send_identity(const int32_t arg);
  int32_t recv_identity();
};

class InheritedProcessor : public SrvProcessor {
 protected:
  boost::shared_ptr<InheritedIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (InheritedProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_identity(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  InheritedProcessor(boost::shared_ptr<InheritedIf> iface) :
    SrvProcessor(iface),
    iface_(iface) {
    processMap_["identity"] = &InheritedProcessor::process_identity;
  }

  virtual ~InheritedProcessor() {}
};

class InheritedProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  InheritedProcessorFactory(const ::boost::shared_ptr< InheritedIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< InheritedIfFactory > handlerFactory_;
};

class InheritedMultiface : virtual public InheritedIf, public SrvMultiface {
 public:
  InheritedMultiface(std::vector<boost::shared_ptr<InheritedIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<boost::shared_ptr<InheritedIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      SrvMultiface::add(*iter);
    }
  }
  virtual ~InheritedMultiface() {}
 protected:
  std::vector<boost::shared_ptr<InheritedIf> > ifaces_;
  InheritedMultiface() {}
  void add(boost::shared_ptr<InheritedIf> iface) {
    SrvMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
  int32_t identity(const int32_t arg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->identity(arg);
    }
    return ifaces_[i]->identity(arg);
  }

};

}}} // namespace

#endif
